#!/bin/bash

# Color codes
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "By default, this package will ${YELLOW}not${NC} make a database host. If you would like to make one, install MariaDB first with:"
echo ""
echo -e "${BLUE}curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash${NC}"
echo -e "${BLUE}apt -y install mariadb-server${NC}"
echo ""
printf "Then, follow this guide made by Pterodactyl: ${BLUE}https://pterodactyl.io/tutorials/mysql_setup.html#creating-a-database-host-for-nodes${NC}\n\n"
echo ""
echo -e "Wings has been normally installed. To configure Wings, please follow this guide: ${BLUE}https://pterodactyl.io/wings/1.0/installing.html#configure${NC}"
echo "Once done, you can verify the configuration if it's correct by running this command:"
echo ""
echo -e "${BLUE}sudo wings --debug${NC}"
echo ""
echo "After verifying, you can start Wings from systemctl using this command:"
echo ""
echo -e "${BLUE}sudo systemctl enable --now wings.service${NC}"
echo ""
echo -e "Thank you for using ${GREEN}my package!${NC}"

